include required("shared.conf")

canton.mediators.mediator {

    storage = ${_shared.storage}
    storage.config.properties.databaseName = "canton_mediator"

    admin-api {
        address = 0.0.0.0
        port = 10042
    }

    monitoring {
        grpc-health-server {
            address = 0.0.0.0
            port = 10043
        }
        http-health-server {
            address = 0.0.0.0
            port = 10044
        }
    }


}