include required("shared.conf")

include required("jwt/unsafe-hmac256.conf")

canton.parameters.non-standard-config = yes

canton.participants.participant {

    init.identity = ${?_shared.identity}

    storage = ${_shared.storage}
    storage.config.properties.databaseName = "canton_unlockit_participant"

    storage.parameters {
        connection-allocation {
            num-ledger-api = 2
            num-reads = 2
            num-writes = 2
        }
        max-connections = 6        
        ledger-api-jdbc-url = ${?_shared.storage.ledger-api-jdbc-url}
    }

    sequencer-client {
        keep-alive-client = ${?_shared.sequencer-client.keep-alive-client}
    }

    // Ledger API Configuration Section
    ledger-api {
        address = 0.0.0.0
        port = 10001
        auth-services = ${?_shared.ledger-api.auth-services}
        keep-alive-server = ${?_shared.ledger-api.keep-alive-server}
        admin-token-config.admin-claim = true
    }

    admin-api {
        address = 0.0.0.0
        port = 10002
        tls = ${?_shared.admin-api-mtls}
        keep-alive-server = ${?_shared.admin-api.keep-alive-server}
    }

    http-ledger-api {
       address = 0.0.0.0
       port = 10005
    }

    monitoring {
        grpc-health-server {
            address = 0.0.0.0
            port = 10003
        }
        http-health-server {
            address = 0.0.0.0
            port = 10004
        }
    }

    parameters = ${?_shared.participant-dev-params}

}