canton {
    remote-sequencer.sequencer {
        public-api {
            address = localhost
            port = 10038
        }
        admin-api {
            address = localhost
            port = 10039
        }
    }
}